<center><h1> 04.- VARIABLES DE TIPO ARRAY Y LIBRERÍA NUMPY </h1></center>

Las variables de tipo $array$, son una estructura de datos que consiste de filas o vectores que contienen cierto número de elementos. A diferencia de las listas, todos los elementos de un array son del mismo tipo, generalmente numérico entero ($integer$) o decimal ($float$).

Para el manejo de este tipo de variables se utiliza la librería $numpy$, la cual cuenta con múltiples funcionalidades desde operaciones básicas de edición hasta operaciones para el álgebra lineal.

In [1]:
# Primero necesitamos llamar o "importar" nuestro módulo, lo hacemos mediante la instrucción 
# "import" y lo renombramos como "np", esto para facilitar el uso dentro del código:
import numpy as np

<h2> ¿Cómo se crea un array? </h2>

1. Se define la función "$np.array(\:)$" osea "del módulo numpy a una variable usar la funcion array" a una variable. 
2. Se define la colección de elementos entre corchetes: $[e_1,\:e_2,\: \ldots \:e_n]$

In [2]:
# Array de tres elementos, matriz de 1 fila por 3 columnas:
ar1x3 = np.array([1, 2, 3])

# Printamos la variable "ar1x3" 
print(ar1x3)

# Llamamos el tipo de dato que es:
print(type(ar1x3))

[1 2 3]
<class 'numpy.ndarray'>


<h3> Tipos de dato para definir arrays: </h3>

Algunas veces es necesario especificar el tipo de dato de los elementos del array, por ej. el tipo de número, ya sean $int$, $float$ o $complex$. Esto se realiza mediante la función "$dtype=$" a la derecha del array.

In [3]:
# Creamos un array de 1x3 que contiene números enteros, pero no se especifica el tipo:
array_normal = np.array([1,2,3])
print(array_normal)

[1 2 3]


In [4]:
# Utilizamos el mismo array especificando el tipo "integer":
array_entero = np.array([1.0, 2.0, 4.0], dtype=int)
print(array_entero)

[1 2 4]


In [5]:
# Utilizamos el mismo array especificando el tipo "float":
array_decimal = np.array([1, 2, 3.1416], dtype=float)
print(array_decimal)

[1.     2.     3.1416]


In [6]:
# Utilizamos el mismo array especificando el tipo "complex":
array_complejo = np.array([1, 2+3j, 3.1416], dtype=complex)
print(array_complejo)

[1.    +0.j 2.    +3.j 3.1416+0.j]


<h3> Arreglos de arreglos: </h3>

Para hacer arrays del tipo $2x2$, $3x3$, $4x4$, etc. solo hace falta agregar más colecciones con la misma cantidad de elementos.  

Un array de $mxn$ es una colección de dos o más colecciones de elementos: 

$[\:[e_1, \:e_2,\: \ldots \:e_n]_1,\:[e_1,\:e_2,\: \ldots \:e_n]_2,\: \ldots \:[e_1,\:e_2,\: \ldots \:e_n]_n\:]$ 

In [7]:
# Arrays de 2x2, 3x3 y 4x4 elementos:

ar2x2 = np.array([[1, 2], [2, 3]])     #los arrays de múltiples filas se pueden escribir de forma lineal

ar3x3 = np.array([[1, 2, 3],           # o situando cada fila debajo de la anterior
                  [5, 7, 8], 
                  [7, 8, 9]])

ar4x4 = np.array([[ 1,  2,  3,  4], 
                  [ 5,  6,  7,  8],    # no importan los saltos de renglon, los elemtos del array se definen
                  [ 9, 10, 11, 12],    # entre los paréntesis de la instrucción "np.array()"
                  [13, 14, 15, 16]])

print('Array 2x2')
print(ar2x2)
print('-')
print('Array 3x3')
print(ar3x3)
print('-')
print('Array 4x4')
print(ar4x4)

Array 2x2
[[1 2]
 [2 3]]
-
Array 3x3
[[1 2 3]
 [5 7 8]
 [7 8 9]]
-
Array 4x4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


<h3> Columnas de datos: </h3>

Una $columna$ es un concepto ampliamente utilizado en el álgebra lineal, un array es un arreglo de datos del tipo $mxn$ donde $n$ define el número de columnas. Si se necesita crear una matriz de dimención $1xn$ (una columna de $n$ elementos) se puede hacer de las dos formas siguientes:

Definiendo cada elemento de la columna dentro de su colección:  

$[\:[c_1], \:[c_2],\: \ldots \:[c_n]\:]$

In [8]:
mat_col = np.array([ [1], [2], [3] ]) # prestar especial atención a como se definen los elementos 

print(mat_col)

[[1]
 [2]
 [3]]


<h3> La función $transpose$ </h3>

Definiendo una colección global con los elementos de la columna dentro del array: $[\:[c_1,\:c_2,\: \ldots \:c_n]\:]$ y usando la función "$np.transpose(\:)$" se genera una nueva variable con la matriz transpuesta.

In [9]:
mat_col2 = np.array([ [4, 5, 10] ]) # prestar especial atención a como se definen los elementos 

mat_col2_trans = np.transpose(mat_col2)

print(mat_col2_trans)

[[ 4]
 [ 5]
 [10]]


<h3> Arrays a partir de otros tipos de datos: </h3>

Dado que $los \:arrays$ en escencia $son \:colecciones \:de \:elementos$ también se pueden crear a partir de variables que sean colecciones, como las $listas$ o las $tuplas$, estas últimas son variables inmutables, pero al utilizarlas para crear una nueva variable de tipo array adquieren las propiedades de los arreglos:

In [10]:
# Definimos tres variables, las cuales tienen las mismas dimenciones 1x3,
# una fila de tres elementos:

ar1 = np.array([12, 15, 5])
ar2 = np.array([6, 8, 7])
ar3 = np.array([0, 1, 1])

print('ar1: ', ar1)
print('ar2: ', ar2)
print('ar3: ', ar3)

ar1:  [12 15  5]
ar2:  [6 8 7]
ar3:  [0 1 1]


In [11]:
# Creamos una nueva variable de tipo array (ar123) de dimenciones 3x3
# (3 filas de tres elementos) a partir de los arrays anteriores: 

ar123 = np.array([ar1, ar2, ar3])

print('ar123:')
print(ar123)
print(type(ar123))

ar123:
[[12 15  5]
 [ 6  8  7]
 [ 0  1  1]]
<class 'numpy.ndarray'>


In [12]:
# Creamos una variable de tipo lista y un array unidimencional de tres elementos:

lis_ej = [2,4,6]

ar_ej = np.array([1,1,1])

# Creamos un nuevo array juntando ar_ej y lis_ej:

ar2_ej = np.array([ar_ej, lis_ej])

print(ar2_ej)
print(type(ar2_ej))

[[1 1 1]
 [2 4 6]]
<class 'numpy.ndarray'>


In [13]:
# Creamos una variable de tipo tupla y un array unidimencional de tres elementos:

tup_ej = (2,4,6)

ar3_ej = np.array([2,4,6])

# Creamos un nuevo array juntando ar_ej y lis_ej:

ar4_ej = np.array([ar3_ej, tup_ej])

print(ar4_ej)
print(type(ar4_ej))

[[2 4 6]
 [2 4 6]]
<class 'numpy.ndarray'>


<h3> Reglas de indexación de colecciones: </h3>

Una de las $ventajas$ de los arreglos es que $se \:puede \:operar \:con \:elementos \:específicos$ de las colecciones, solo se debe tener especial cuidado de seguir la $regla \:de \:indexación$. 

Para operar filas en específico se hace referencia a ellas mediante la forma $A[i]$ osea "fila $i$ de la matriz $A$".

In [14]:
# De los arreglos ar2x2, ar3x3 y ar4x4

print('Segunda fila de la variable ar2x2')
print(ar2x2[1])
print('Tercera fila de la variable ar3x3')
print(ar3x3[2])
print('Primer fila de la variable ar4x4')
print(ar4x4[0])

Segunda fila de la variable ar2x2
[2 3]
Tercera fila de la variable ar3x3
[7 8 9]
Primer fila de la variable ar4x4
[1 2 3 4]


<h3> Reglas de indexación de elementos dentro de las colecciones: </h3>

Para operar con un elemento en específico dentro de una fila lo invocamos de la forma $A[i][j]$ o "elemento $j$ de la fila $i$ de la matriz $A$".

In [15]:
# Printamos individualmente los elementos del arreglo ar1x3

print('Primer elemento de ar1x3')
print(ar1x3[0])
print('Segundo elemento de ar1x3')
print(ar1x3[1])
print('Tercer elemento de ar1x3')
print(ar1x3[2])
print('Segundo elemento de la segunda fila de la variable ar2x2')
print(ar2x2[1][1])
print('Primer elemento de la tercera fila de la variable ar3x3')
print(ar3x3[2][0])
print('Tercer elemento de la primer fila de la variable ar4x4')
print(ar4x4[0][2])

Primer elemento de ar1x3
1
Segundo elemento de ar1x3
2
Tercer elemento de ar1x3
3
Segundo elemento de la segunda fila de la variable ar2x2
3
Primer elemento de la tercera fila de la variable ar3x3
7
Tercer elemento de la primer fila de la variable ar4x4
3


<h2> Arreglos especiales: </h2>

Existen arrays especiales como la matriz de ceros, la matriz de unos, la matriz identidad, matrices vacías y matrices de números consecutivos en una dimensión. Estos arreglos se invocan mediante los comandos $ones$, $zeros$, $identity$, $empty$, $arrange$, etc.

<h3> Matriz $zeros$: </h3>

La matriz $zeros$ devuelve una variable de tipo array en la que todos sus elementos son ceros,  a esta matriz hay que especificar sus dimenciones $np.zeros((m,n))$ (filas x columnas):

In [16]:
ceros = np.zeros((3,4))
print('Matriz zeros de tres filas y cuatro columnas:')
print(ceros)

Matriz zeros de tres filas y cuatro columnas:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


<h3> Matriz $ones$: </h3>

La matriz $ones$ es similar a la matriz $zeros$, esta nos devolverá una variable de tipo array en la que todos sus elementos son unos, a esta matriz hay que especificar sus dimenciones $np.ones((m,n))$ (filas x columnas):  

In [17]:
unos = np.ones((3,4))
print('Matriz unos de tres filas y cuatro columnas:')
print(unos)

Matriz unos de tres filas y cuatro columnas:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


<h3> Matriz $identity$: </h3>

Con la matriz $identity$ se crean arrays con la propiedad de la $matriz \:identidad$ (donde la diagonal principal se compone de unos), para esta solo debemos especificar una dimención pues es del tipo $nxn$ (el número de filas es igual al de columnas), se invoca con la función $np.identity(n)$:

In [18]:
ident4 = np.identity(4)
print('Matriz identity de cuatro filas y cuatro columnas:')
print(ident4)

Matriz identity de cuatro filas y cuatro columnas:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


<h3> Matriz $arange$: </h3>

La matriz de tipo $arange$ crea un array de una dimención que consta de los elementos en secuencia desde un valor de inicio hasta un valor final y especificando un tamaño de salto, retornando los valores correspondientes a cada salto, existen dos formas de definir este tipo de arreglos:

1. Invocando la función $np.arange(valor_i, \:valor_f, \:salto)$, de esta forma se tendrá un array unidimencional en el que se especifique el valor inicial y final de la secuencia y el valor de salto en el cual se retornaran los valores:

In [19]:
d1 = np.arange(0,15,1)

d2 = np.arange(0,10,2)

print('Arreglo de los elementos contenidos entre los índices 0 al 15, con saltos de uno en uno:')
print(d1)
print('-')
print('Arreglo de los elementos contenidos entre los índices 0 al 10, con saltos de dos en dos:')
print(d2)

Arreglo de los elementos contenidos entre los índices 0 al 15, con saltos de uno en uno:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
-
Arreglo de los elementos contenidos entre los índices 0 al 10, con saltos de dos en dos:
[0 2 4 6 8]


2. Invocando la función $np.arange(n).reshape(i,j)$ de esta forma se tendrá un array multidimencional de $n$ elementos que serán organizados a la forma $i_{filas}\:x\:j_{columnas}$:

In [20]:
e1 = np.arange(10).reshape(2, 5)

e2 = np.arange(10).reshape(5, 2)

print('Arreglo 2x5 de 10 elementos:')
print(e1)
print('-')
print('Arreglo 5x2 de 10 elementos:')
print(e2)

Arreglo 2x5 de 10 elementos:
[[0 1 2 3 4]
 [5 6 7 8 9]]
-
Arreglo 5x2 de 10 elementos:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


<h3> Matriz $linspace$: </h3>

La matriz $linspace$ devuelve un array que extrae de un arreglo lineal de valores inicial a final un determinado número de valores que equidistan entre si, este array se invoca con la función: 

- $np.linspace(v_{inicio},\:v_{final},\:n)$:  

In [21]:
ar_lin1 = np.linspace(0,10,3)

ar_lin7 = np.linspace(0,5,7)

print('Array de tipo linspace que extrae 3 valores equidistantes del 0 al 10:')
print(ar_lin1)
print('-')
print('Array de tipo linspace que extrae 7 valores equidistantes del 0 al 5:')
print(ar_lin7)

Array de tipo linspace que extrae 3 valores equidistantes del 0 al 10:
[ 0.  5. 10.]
-
Array de tipo linspace que extrae 7 valores equidistantes del 0 al 5:
[0.         0.83333333 1.66666667 2.5        3.33333333 4.16666667
 5.        ]


<h3> Matriz $logspace$: </h3>

La matriz $logspace$ devuelve un array que extrae de un arreglo logaritmico de valores inicial a final un determinado número de valores que equidistan entre si, este array se invoca con la función: 

- $np.logspace(\text{exponente de la potencia_inicial}, \text{exponente de la potencia_final}, \:num=, \:base=)$ 

In [22]:
# Creamos un arreglo logarítmico de 10 elementos del 0 al 1000
ar_log1 = np.logspace(0, 3, num=10, base=10)

print('Array de tipo logspace que devuelve 10 valores del 0 al 1000 en log base 10:')
print(ar_log1)

Array de tipo logspace que devuelve 10 valores del 0 al 1000 en log base 10:
[   1.            2.15443469    4.64158883   10.           21.5443469
   46.41588834  100.          215.443469    464.15888336 1000.        ]


<h3> Matriz $full$: </h3>

La matriz $full$ devuelve un array lineal de $i$ elementos de valor $n$, se invoca con la función: 

- $np.full(i,\:n)$

In [23]:
mat_full = np.full(5,3.1416)

print(mat_full)

[3.1416 3.1416 3.1416 3.1416 3.1416]


<h3> Atributos de los Arrays: </h3>

Llamando las siguientes funciones después de "$.np$" se pueden conocer los atributos de los arrays:

- $ndim(\:)$ devuelve el número de ejes
- $shape(\:)$ devuelve una tupla con las dimenciones $mxn$
- $size(\:)$ devuelve el número de elementos dentro del array 

Recuerde que los arrays tienen ejes o dimenciones de la siguiente forma:

- 1 eje $A[m]$
- 2 ejes $A[m\:x\:n]$ 
- 3 ejes $A[m\:x\:n\:x\:l]$

In [24]:
# Tomemos como ejemplo la matriz ar4x4 y apliquemos las funciones anteriores:

print('El número de ejes del array ar4x4 son: ', ar4x4.ndim)
print(' ')
print('Las dimenciones mxn del array ar4x4 son: ', ar4x4.shape)
print(' ')
print('El número de elementos del array ar4x4 son: ', ar4x4.size)

El número de ejes del array ar4x4 son:  2
 
Las dimenciones mxn del array ar4x4 son:  (4, 4)
 
El número de elementos del array ar4x4 son:  16


<h2> Operaciones con arrays </h2>

Con las variables del tipo array se pueden realizar algunas operaciones que corresponden al álgebra lineal y al álgebra vectorial, como el producto escalar y el producto punto, además de suma, resta y multiplicación.

In [25]:
matA = np.array([[1,2,3], [4,5,6], [7,8,9]])      # matriz 3x3

matB = np.array([[2,4,6], [8,10,12], [14,16,18]]) # matriz 3x3

matC = np.array([[22,2,93], [3.1416, 5.5, 50]])   # matriz 2x3

matD = matC.T                                     # matriz 3x2 (transpuesta de matC)

matE = np.array([[2, -2], [-3.14, 1]])            # matriz 2x2

print('matA dimenciones 3x3')
print(matA)
print('-')
print('matB dimenciones 3x3')
print(matB)
print('-')
print('matC dimenciones 2x3')
print(matC)
print('-')
print('matD dimenciones 3x2')
print(matD)
print('-')
print('matE dimenciones 2x2')
print(matE)

matA dimenciones 3x3
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-
matB dimenciones 3x3
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
-
matC dimenciones 2x3
[[22.      2.     93.    ]
 [ 3.1416  5.5    50.    ]]
-
matD dimenciones 3x2
[[22.      3.1416]
 [ 2.      5.5   ]
 [93.     50.    ]]
-
matE dimenciones 2x2
[[ 2.   -2.  ]
 [-3.14  1.  ]]


<h3> Suma y resta de arreglos: </h3>

Recordar que para realizar $sumas$ y $restas$ las matrices deben tener las mismas dimenciones:

In [27]:
print('Suma matA + matB:')
print(matA + matB)
print('-')
print('Resta matA - matB:')
print(matA - matB)

Suma matA + matB:
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
-
Resta matA - matB:
[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]


<h3> Multiplicación de arreglos: </h3>

Para $multiplicar$ matrices se utiliza la función $np.dot(A,B)$. Recordar que siempre el número de columnas de la primera matriz debe ser igual al número de filas de la segunda "A=axn y B=nxb"  y que esta regla no es conmutativa para todos los casos, solo cuando ambas matrices son del tipo nxn:

In [28]:
print('El producto de matA de 3x3 por matB de 3x3:')
print(np.dot(matA, matB))

El producto de matA de 3x3 por matB de 3x3:
[[ 60  72  84]
 [132 162 192]
 [204 252 300]]


In [29]:
print('El producto de matD de 3x3 por matE de 2x2:')
print(np.dot(matD, matE))

El producto de matD de 3x3 por matE de 2x2:
[[  34.135376  -40.8584  ]
 [ -13.27        1.5     ]
 [  29.       -136.      ]]


<h3> Multiplicación de arreglos de dimenciones diferentes: </h3>

Producto de matrices de dimenciones diferentes, donde se respeta la regla que el número de columnas de la primera matriz es igual al número de filas de la segunda matriz:

In [ ]:
print('El producto de matC de 3x2 por matA de 2x2:')
print(np.dot(matC, matA))

In [ ]:
print('El producto de matC de 2x3 por matA de 3x3:')
print(np.dot(matC, matA))

In [ ]:
print(matA)
print(type(matA))

print(matB)
print(type(matB))

In [ ]:
#matC = np.dot(matB,matA)
matC = matB * matA

print(matC)