<center><h1> 05.- ESTRUCTURAS DE CONTROL </h1></center>

Las $estructuras\:de\:control$ son instrucciones o estructuras que realizan cierta acción, siempre y cuando se cumpla o no cierta condición establecida (sean $True$ o $False$).

<h2> Estructuras condicionales "$if$ - $elif$ - $else$": </h2>

La estructura $if$ permite dividir el flujo del programa en base a una evaluación lógica definida por una condición y decidir qué acción ejecuta en base a la condición a cumplir. Normalmente esta estructura se acompaña de un $else$ para realizar una acción cuando no se cumpla la condición y uno o más $elif$ para cuando no se cumple una primera condición pero si una o más adicionales.

In [2]:
# La sentencia "if" se ejecutará cuando la condición resulte en "True"

if True:                                                 # Siempre poner ":" despues de la sentencia
    print('Sentencia if solo entra con valor verdadero') # Siempre indentar con un espacio tabular después de la sentencia

Sentencia if solo entra con valor verdadero


In [3]:
# La sentencia "if" no se ejecuta cuando las condiciones resultan en "False"

if False:
    print('Sentencia if solo entra con valor verdadero') # No imprime porque la condición es "False"

In [9]:
# La sentencia "else" se cumple como una segunda condición, 
# normalmente en el caso contrario a la sentencia "if" 

nombre = float(input('Ingresa tu edad: '))             
if nombre < 18:                                        # Primer condición o condición principal
    print('Eres menor de edad, no puedes pasar')       # Instrucción correspondiente a primera condición
    nombre = float(input('Ingresa una nueva edad: '))
elif nombre = 18:                                      # Condición adicional al "if" principal
    print('Eres adulto, bienvenido')                   # Instrucción correspondiente
else:                                                  # Caso contrario al "if" principal
    print('Eres adulto, bienvenido')                   # Instrucción correspondiente al "else"

SyntaxError: invalid syntax (<ipython-input-9-554e35eff62d>, line 8)

In [5]:
# Estructura "if" encadenada o anidada (con una subestructura "if")

a = float(input('Número a: '))      # al ingresar lo números por input  
b = float(input('Número b: '))      # ... se printan durante la ejecución

if a == b:
    print('a y b son iguales')
else:
    print('a y b son diferentes')
    if a > b:
        print('a es mayor que b')
    else:
        print('a es menor que b')

Número a: 75
Número b: 3.1416
a y b son diferentes
a es mayor que b


In [6]:
cal = float(input('Ingrese calificación: '))

if cal <= 5:
    print('Repites curso')
elif cal == 5:
    print('Presenta extraordinario')
elif cal > 5 and cal <= 7:
    print('Presenta ordinario')
elif cal > 7 and cal <= 9:
    print('Presenta ordinario a decisión')
elif cal == 10:
    print('Eres un master')

Ingrese calificación: 10
Eres un master


<h3> Operadores ternarios: </h3>

Un $operador$ $ternario$ sirve para evaluar si una expresión resulta $True$ o $False$ mediante una sola línea de código. Los operadores ternarios pueden usarse para resumir expresiones lógicas $if\:elif\:else$.

In [5]:
# Se tiene la siguiente expresión lógica "if else":
edad = 14

if (18 <= edad < 65):
    print('Eres un adulto')
else:
    print('No eres adulto')

No eres adulto


In [6]:
# Se puede resumir mediante un operador ternario y guardarlo en una variable como sigue:
mensaje = 'Eres un adulto' if 18 <= edad < 65 else 'No eres adulto'

print(mensaje)

No eres adulto


<h2> Estructura de bucle condicional "$while$": </h2>

La estructura $while$ realiza una instrucción de forma iterada "$mientras$" se cumpla o no una condición; hasta que el estado de la condición se cumpla con un $True$ o un $not\:True$ según se defina al declarar la instrucción.

In [7]:
num = 0   # Se define una variable inicial
while num <= 5:               # Hasta que se cumpla la instrucción declarada se realizan las siguientes instrucciones:
    num += 1                  # se realiza la acción "sumar uno a la variable"...
    print('Iteración', num)   # y se printa el nuevo valor de la variable...

Iteración 1
Iteración 2
Iteración 3
Iteración 4
Iteración 5
Iteración 6


In [17]:
lista = [1,2,3,4,5,6,7,8,9,10] # Definimos una lista con diez elementos (no son números, son str)
indice = 0                     # Inicializamos una variable en "0"

while indice < len(lista):    # Mientras el valor numérico de "indice" sea menor al número de elementos de "lista"...
    print(lista[indice])      # printar cada elemento de la lista
    indice += 1               # sumar 1 a la variable "indice"

1
2
3
4
5
6
7
8
9
10


In [8]:
#---------------------- Ciclo "while" con una variable tipo "array"

import numpy as np             # Importamos el paquete "numpy" (paquete de matemáticas) como "np"
num = np.array([[0,0],[5,5]])  # Asignamos un array 2x2 a la variable "num"

while np.all(num[0] != num[1]):      # Mientras los vectores de "num" sean diferentes se realizan las instrucciones...
    num[0] += 1                      # Sumar 1 a los valores del primer vector del array "num"
    
    equi = []                        # Ciclo "for" dentro de la estructura "while"
    for i, j in zip(num[0], num[1]):
        eq = abs(i - j)
        equi.append(eq)
    equilibrio = np.array([equi[0], equi[1]]) # Definimos la variable "equilibrio" como resultado del "for"

else:    # Hasta que la condición inicial resulte "false" se realizan las sig instrucciones
    print('nuevo num')
    print(num)
    print('equilbrio')
    print(equilibrio)

nuevo num
[[5 5]
 [5 5]]
equilbrio
[0 0]


In [9]:
#------------------ Ciclo "while" con una variable tipo "array" y una función definida dentro del ciclo

import numpy as np
num = np.array([[0,0],[5,5]])

def equilibrio_quimico(num):      #se define la función "equilibrio_quimico" con el ciclo "for" del block anterior
    equi = []                        
    for i, j in zip(num[0], num[1]):
        eq = abs(i - j)
        equi.append(eq)
    equilibrio = np.array([equi[0], equi[1]])
    return equilibrio
equilibrio = equilibrio_quimico(num)    # se asigna el resultado de la función a la variable "equilibrio"

while np.all(num[0] != num[1]): # Mientras los vectores de "num" sean diferentes se realizan las instrucciones...
    num[0] += 1                 # Sumar 1 a los valores del primer vector del array "num"  
    equilibrio_quimico(num)     # Se ejecuta la función "equilibrio_quimico" con el nuevo valor de "num"
    print('----------')
    print('nuevo num')          # Se printan las siguientes cadenas y variables
    print(num)
    print('equilbrio')
    print(equilibrio)
    
# La última ejecución resulta en "false" (los vectores de "num" son iguales) 
# hasta ese momento se deja de cumplir la condición y termina el ciclo "while"

----------
nuevo num
[[1 1]
 [5 5]]
equilbrio
[5 5]
----------
nuevo num
[[2 2]
 [5 5]]
equilbrio
[5 5]
----------
nuevo num
[[3 3]
 [5 5]]
equilbrio
[5 5]
----------
nuevo num
[[4 4]
 [5 5]]
equilbrio
[5 5]
----------
nuevo num
[[5 5]
 [5 5]]
equilbrio
[5 5]


In [1]:
#-------------------------- Usando "if", "while", "else", "elif" en un solo código

print('Ingresa el número de que operación quieres realizar')
inicio = input('Escribe "run" para iniciar: ')
while (inicio == 'run'):
    print("""Ingresa el número de la operación que deseas realizar:
    1 - Suma
    2 - Resta
    3 - Multiplicación
    4 - División
    5 - Salir""")
    option = input()
    if option == '1':
        a = float(input('Ingrese el primer número: '))
        b = float(input('Ingrese el segundo número: '))
        print('El resultado de la suma es', a + b)
        print('Si desea continuar calculando elija la opción que sesée, si no, ingrese 5')
    elif option == '2':
        a = float(input('Ingrese el primer número: '))
        b = float(input('Ingrese el segundo número: '))
        print('El resultado de la resta es', a - b)
        print('Si desea continuar calculando elija la opción que sesée, si no, ingrese 5')
    elif option == '3':
        a = float(input('Ingrese el primer número: '))
        b = float(input('Ingrese el segundo número: '))
        print('El resultado de la multiplicación es', a * b)
        print('Si desea continuar calculando elija la opción que sesée, si no, ingrese 5')
    elif option == '4':
        a = float(input('Ingrese el primer número: '))
        b = float(input('Ingrese el segundo número: '))
        print('El resultado de la división es', a / b)
        print('Si desea continuar calculando elija la opción que sesée, si no, ingrese 5')
    else:
        print('Terminó la ejecución')
        break

Ingresa el número de que operación quieres realizar
Escribe "run" para iniciar: run
Ingresa el número de la operación que deseas realizar:
    1 - Suma
    2 - Resta
    3 - Multiplicación
    4 - División
    5 - Salir
2
Ingrese el primer número: 10
Ingrese el segundo número: 15
El resultado de la resta es -5.0
Si desea continuar calculando elija la opción que sesée, si no, ingrese 5
Ingresa el número de la operación que deseas realizar:
    1 - Suma
    2 - Resta
    3 - Multiplicación
    4 - División
    5 - Salir
5
Terminó la ejecución


<h2> Estructura repetitiva "$for$": </h2>

El ciclo $for$ es una estructura que ejecuta una o varias instrucciones de forma iterada. Las instrucciones del ciclo $for$ se iteran un número determinado de veces, que puede estar definido por el número de elementos dentro de una lista, dentro de un array, etc. 

El ciclo termina cuando no hay elemento sobre el cual iterar.

In [18]:
nombre = 'Rafael'      # Se define una variable, en este caso de tipo "str"
for letra in nombre:   # Por cada elemento de la variable "nombre" realiza lo sig...
    print(letra)       # printa cada elemento de la variable "nombre"

R
a
f
a
e
l


In [32]:
# Series de tablas de multiplicar con ciclo "for"

import numpy as np
a = np.array(range(1,11)) # se define array "a" de longitud 11 elementos
b = np.array(range(1,11)) # se define array "b" de longitud 11 elementos

c = []         # se define una lista "c" vacía
for i in a:    # para cada elemento del array "a"
    multiplicación = i * b    # se multiplica por el array "b"
    c.append(multiplicación)  # los valores de "multiplicación" se guardan en "c"
    array_c = np.array(c)     # array con los valores de "multiplicación"
matriz_multiplicación = np.array(array_c)  # se guardan en una variable array de arrays "multiplicación"
print(matriz_multiplicación)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [34]:
lista = np.array(range(1,11))
for i in lista:
    print(i)         

1
2
3
4
5
6
7
8
9
10


In [35]:
lista = [1,2,3,4,5,6,7,8,9,10]
ind = 0

for rec in lista:
    lista[ind] *= 10
    ind += 1
    print(lista)               #si meto el print dentro del for pasa esto

[10, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 20, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 20, 30, 4, 5, 6, 7, 8, 9, 10]
[10, 20, 30, 40, 5, 6, 7, 8, 9, 10]
[10, 20, 30, 40, 50, 6, 7, 8, 9, 10]
[10, 20, 30, 40, 50, 60, 7, 8, 9, 10]
[10, 20, 30, 40, 50, 60, 70, 8, 9, 10]
[10, 20, 30, 40, 50, 60, 70, 80, 9, 10]
[10, 20, 30, 40, 50, 60, 70, 80, 90, 10]
[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


In [5]:
for i in range(20):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
